CREATE TABLE CONTACT_MESSAGE (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(250) NOT NULL,
	EMAIL VARCHAR(250) NOT NULL,
	MESSAGE VARCHAR (4000) NOT NULL,
	REMOTE_ADDRESS VARCHAR(100) NOT NULL,
	CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	UPDATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	
	PRIMARY KEY PK_CONTACT_MESSAGE (ID)
);